package main

import (
	"encoding/json"
	"fmt"
	"os"
	"text/tabwriter"

	"github.com/spf13/cobra"
)

var emailCmd = &cobra.Command{
	Use:   "email",
	Short: "Manage AWS SES email domain integrations",
}

var emailSetupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Setup an email sending domain with SES",
	RunE: func(cmd *cobra.Command, args []string) error {
		orgID, _ := cmd.Flags().GetString("org")
		if orgID == "" {
			orgID = cfg.OrgID
		}
		projectID, _ := cmd.Flags().GetString("project")
		domainName, _ := cmd.Flags().GetString("domain")

		if orgID == "" || projectID == "" || domainName == "" {
			return fmt.Errorf("--org, --project, and --domain are required")
		}

		body := map[string]string{"domain": domainName}
		var resp map[string]any
		path := fmt.Sprintf("/api/v1/orgs/%s/projects/%s/email/setup", orgID, projectID)
		if err := apiClient.Post(path, body, &resp); err != nil {
			return err
		}

		fmt.Println("┌─ Cost Estimate ──────────────────────────────┐")
		fmt.Println("│ Amazon SES Outbound Email                    │")
		fmt.Println("│                                              │")
		fmt.Println("│  Outbound:     $0.10 per 1,000 emails        │")
		fmt.Println("│  Data Transfer:$0.09/GB                      │")
		fmt.Println("│  ─────────────────────────────               │")
		fmt.Println("│  Estimated:    ~$1.00/10K emails             │")
		fmt.Println("└──────────────────────────────────────────────┘")
		fmt.Printf("Email Setup Initiated for domain %s (Status: %s)\n", resp["db_name"], resp["status"])
		fmt.Println("Next steps: DNS verification tokens are being generated by SES. Run 'capsule email stats' to verify.")
		return nil
	},
}

var emailTestCmd = &cobra.Command{
	Use:   "test",
	Short: "Send a test email from the verified domain",
	RunE: func(cmd *cobra.Command, args []string) error {
		orgID, _ := cmd.Flags().GetString("org")
		if orgID == "" {
			orgID = cfg.OrgID
		}
		projectID, _ := cmd.Flags().GetString("project")
		toEmail, _ := cmd.Flags().GetString("to")

		if orgID == "" || projectID == "" || toEmail == "" {
			return fmt.Errorf("--org, --project, and --to are required")
		}

		body := map[string]string{"to": toEmail}
		var resp map[string]string
		path := fmt.Sprintf("/api/v1/orgs/%s/projects/%s/email/test", orgID, projectID)
		if err := apiClient.Post(path, body, &resp); err != nil {
			return err
		}

		fmt.Println(resp["message"])
		return nil
	},
}

var emailStatsCmd = &cobra.Command{
	Use:   "stats",
	Short: "View SES sending and bounce analytics",
	RunE: func(cmd *cobra.Command, args []string) error {
		orgID, _ := cmd.Flags().GetString("org")
		if orgID == "" {
			orgID = cfg.OrgID
		}
		projectID, _ := cmd.Flags().GetString("project")

		if orgID == "" || projectID == "" {
			return fmt.Errorf("--org and --project are required")
		}

		type emailStats struct {
			Sent       int `json:"sent"`
			Delivered  int `json:"delivered"`
			Bounces    int `json:"bounces"`
			Complaints int `json:"complaints"`
		}

		var stats emailStats
		path := fmt.Sprintf("/api/v1/orgs/%s/projects/%s/email/stats", orgID, projectID)
		if err := apiClient.Get(path, &stats); err != nil {
			return err
		}

		out, _ := cmd.Flags().GetString("output")
		if out == "json" {
			return json.NewEncoder(os.Stdout).Encode(stats)
		}

		w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
		fmt.Fprintln(w, "SENT\tDELIVERED\tBOUNCES\tCOMPLAINTS\tDELIVERY RATE")
		rate := 0.0
		if stats.Sent > 0 {
			rate = float64(stats.Delivered) / float64(stats.Sent) * 100.0
		}
		fmt.Fprintf(w, "%d\t%d\t%d\t%d\t%.2f%%\n", stats.Sent, stats.Delivered, stats.Bounces, stats.Complaints, rate)
		return w.Flush()
	},
}

func init() {
	emailSetupCmd.Flags().String("org", "", "Org ID")
	emailSetupCmd.Flags().String("project", "", "Project ID")
	emailSetupCmd.Flags().String("domain", "", "Email domain to configure")

	emailTestCmd.Flags().String("org", "", "Org ID")
	emailTestCmd.Flags().String("project", "", "Project ID")
	emailTestCmd.Flags().String("to", "", "Recipient email address")

	emailStatsCmd.Flags().String("org", "", "Org ID")
	emailStatsCmd.Flags().String("project", "", "Project ID")

	emailCmd.AddCommand(emailSetupCmd, emailTestCmd, emailStatsCmd)
	rootCmd.AddCommand(emailCmd)
}
